name: Update Build Number

on:
  push:
    branches:
      - main

jobs:
  update-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Insert Commit SHA into HTML
      run: |
        python insert_commit_sha.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add index.html
        git commit -m "Update build number with commit SHA"
        git push
